version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # Specify the .NET version you are using
    commands:
      - echo Installing .NET Core...
      - dotnet --version

  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
      - echo publish the project...
      - dotnet publish -c Release -o ./publish
      

  post_build:
    commands:
      - echo Running tests...
      - dotnet test --no-build --verbosity normal

artifacts:
  files:
    - '**/*'
  discard-paths: yes  
  base-directory: './publish'