version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS 
  build:
    commands:
      - dotnet restore net-app-web/WebApplication1.sln
      - dotnet build net-app-web/WebApplication1.sln